dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - embeddings
  corpus:
    root: example/data/
    train_path: en_ewt-ud-train.conllu
    dev_path: en_ewt-ud-dev.conllu
    test_path: en_ewt-ud-test.conllu
  batch_size: 1
model:
  hidden_dim: 1024 # hidden dim
  model_type: BERT-disk # BERT-disk, ELMo-disk, 
  use_disk: False
  model_layer: 16 # BERT-base: {1,...,12}; ELMo: {1,2,3}
probe:
  task_signature: word # word, word_pair
  task_name: parse-depth
  maximum_rank: 1024
  psd_parameters: True
  depth_params_path: example/data/bertlarge16-depth-probe.params
  distance_params_path: example/data/bertlarge16-distance-probe.params
probe_training:
  epochs: 30
  loss: L1
reporting:
  root: example/results
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions
  reporting_methods:
    - spearmanr
      #- image_examples
    - root_acc
